from api.constants import MIN_AMOUNT, MIN_COOKING_TIME

INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64
RECIPE_NAME_MAX_LENGTH = 256

MIN_COOKING_TIME_MINUTES = MIN_COOKING_TIME
COOKING_TIME_VALIDATOR_MSG = (
    f"Время должно быть не менее {MIN_COOKING_TIME_MINUTES} минуты"
)

MIN_INGREDIENT_AMOUNT = MIN_AMOUNT
INGREDIENT_AMOUNT_VALIDATOR_MSG = (
    f"Требуется хотя бы {MIN_INGREDIENT_AMOUNT} единица"
)

VERBOSE_INGREDIENT = "Ингредиент"
VERBOSE_INGREDIENTS = "Ингредиенты"
