

USER_USERNAME_MAX_LENGTH = 150
USER_EMAIL_MAX_LENGTH = 254
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150

USER_USERNAME_VERBOSE_NAME = 'Логин'
USER_EMAIL_VERBOSE_NAME = 'Адрес электронной почты'
USER_FIRST_NAME_VERBOSE_NAME = 'Имя'
USER_LAST_NAME_VERBOSE_NAME = 'Фамилия'
USER_AVATAR_VERBOSE_NAME = 'Аватар'

USER_AVATAR_UPLOAD_PATH = 'avatars/'

USER_META_VERBOSE_NAME = 'Пользователь'
USER_META_VERBOSE_NAME_PLURAL = 'Пользователи'

SUBSCRIPTION_USER_VERBOSE_NAME = 'Подписчик'
SUBSCRIPTION_AUTHOR_VERBOSE_NAME = 'Автор'
SUBSCRIPTION_META_VERBOSE_NAME = 'Подписка'
SUBSCRIPTION_META_VERBOSE_NAME_PLURAL = 'Подписки'

UNIQUE_SUBSCRIPTION_CONSTRAINT_NAME = 'unique_subscription'
PREVENT_SELF_SUBSCRIPTION_CONSTRAINT_NAME = 'prevent_self_subscription'
